### ISSUE TITLE
Screenshot needed

### ISSUE THREAD

**Issue by likendev** [likendev/catppuccin-mobaxterm#1]
Need someone to help generating a screenshot for README

**Comment by DanielZhang111** [comment]
Can I get assigned?

**Comment by likendev** [comment]
> Can I get assigned?

Hi @DanielZhang111, there is no assignment process for this repo. Feel free to proceed to open a Pull Request

**Comment by DanielZhang111** [comment]
Ok! All I need to do is submit a screenshot?

**Comment by likendev** [comment]
> Ok! All I need to do is submit a screenshot?

Hi, this is a community project for Catppuccin, you may refer to the guide [here](https://github.com/catppuccin/catppuccin/blob/main/docs/port-creation.md):

> The main preview image should be an image generated by [catwalk](https://github.com/catppuccin/toolbox#-catwalk). (e.g. [vscode](https://github.com/catppuccin/vscode#catppuccin-for-vscode) and [discord](https://github.com/catppuccin/discord#catppuccin-for-discord))

For this one, I'll need help to load the theme into MobaXterm and take screenshot accordingly, then generate the screenshot following the guide, then amend the README in this repo. 

Kindly follow [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) commit style. 

Appreciate your help!

**Comment by DanielZhang111** [comment]
Ok! I will check it out and work on it when I get home!

**Comment by likendev** [comment]
Hi @DanielZhang111 I've added screenshots in assets/ folder. Kindly add the screenshots into README file accordingly. Thank you!

**Comment by DanielZhang111** [comment]
Ok thanks!

**Comment by likendev** [comment]
I've added in the screenshot myself. Thanks!
